# Generated by Django 5.2 on 2025-04-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_notification_thread_tags_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Query',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='course',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='tags',
        ),
    ]
